units:
  units:
  # kx and ky allow for easy- easi-er switching between MX and Choc.
  kx: u
  ky: u
  px: kx + 2
  py: ky + 2

points:
  zones:
    matrix:
      columns:
        c1:
        c2:
        c3.key.stagger: u/4
        c4:
          key.stagger: u/8
          rows.r4.skip: true
        c5:
          key.stagger: -u/8
          rows.r4.skip: true
        c6:
          key.stagger: -u/8
          rows.r4.skip: true
      rows:
        r4:
        r3:
        r2:
        r1:
    thumbfan:
      anchor:
        - ref: matrix_c4_r3
          shift: [9.5,-22]
      columns:
        c4:
        c5.key:
          splay: -15
          stagger: -2.7
          spread: u + 2
        c6.key:
          splay: 75
          stagger: 2
          spread: u + 3.5
      rows:
        r0:

outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  outline:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_c1_r1
          shift: [-0.55px, 0.55py]
        - ref: matrix_c3_r1
          shift: [-0.55px, 0.35py]
        - ref: matrix_c3_r1
          shift: [-0.55px, 0.6py]
        - ref: matrix_c6_r1
          shift: [-0.4px, 0.75py]
        - ref: matrix_c6_r1
          shift: [-0.4px, 0.55py]
        - ref: matrix_c6_r1
          shift: [0.5px, 0.5py]
        - ref: matrix_c6_r1
          shift: [1.5px, 0.5py]
        - ref: thumbfan_c6_r0
          shift: [0.55px, -0.6py]
        - ref: thumbfan_c6_r0
          shift: [-0.65px, -0.6py]
        - ref: thumbfan_c6_r0
          shift: [-0.7px, 0.25py]
        - ref: thumbfan_c5_r0
          shift: [-0.4px, -0.55py]
        - ref: thumbfan_c4_r0
          shift: [-0.45px, -0.5py]
        - ref: thumbfan_c4_r0
          shift: [-0.55px, -0.5py]
        - ref: thumbfan_c4_r0
          shift: [-0.55px, 0.35py]
        - ref: thumbfan_c4_r0
          shift: [-0.8px, 0.35py]
        - ref: thumbfan_c4_r0
          shift: [-0.8px, -0.55py]
        - ref: matrix_c3_r4
          shift: [-0.3px, -0.6py]
        - ref: matrix_c3_r4
          shift: [-0.3px, -0.8py]
        - ref: matrix_c1_r4
          shift: [-0.55px, -0.6py]
        - ref: matrix_c1_r1
          shift: [-0.55px, 0.5py]
  combo:
    - name: outline
    - operation: stack
      name: keys